export const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS';
export const GET_RESTAURANT_SUCCESS = 'GET_RESTAURANT_SUCCESS';

export const GET_RESTAURANTS_FAILURE = 'GET_RESTAURANTS_FAILURE';
export const GET_RESTAURANT_FAILURE = 'GET_RESTAURANT_FAILURE';

export const SET_SORT_TYPE = 'SET_SORT_TYPE';
export const SET_SORT_ORDER = 'SET_SORT_ORDER';

export const SORT_TYPES = {
  RATING: 'RATING',
  PRICE: 'PRICE',
};
